version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    resource_class: medium
    working_directory: ~/work
    steps:
      - run:
          name: Build
          command: echo meocoder 
workflows:
  version: 2
  constantly_build:
    triggers:
      - schedule:
          cron: "0 10 * * 2"
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - build